### ISSUE TITLE
undefined symbol: clang_getCompletionFixIt on Ubuntu18.04

### ISSUE THREAD

**Issue by TsutomuNakamura** [TsutomuNakamura/dotfiles#160]
When open vim then the error has occured on Ubuntu 18.04.
```
Traceback (most recent call last):
  File "/home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/extra_conf_store.py", line 99, in _CallGlobalExtraConfMethod
    module = Load( global_ycm_extra_conf, force = True )
  File "/home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/extra_conf_store.py", line 178, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "/home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 507, in LoadPythonSource
    return imp.load_source( name, pathname )
  File "/home/me/.ycm_extra_conf.py", line 19, in <module>
    import ycm_core
ImportError: /home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so: undefined symbol: clang_getCompletionFixIt
YYYY-MM-DD HH:MM:SS,sss - ERROR - /home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so: undefined symbol: clang_getCompletionFixIt
Traceback (most recent call last):
  File "/home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 639, in ImportAndCheckCore
    ycm_core = ImportCore()
  File "/home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 630, in ImportCore
    import ycm_core as ycm_core
ImportError: /home/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so: undefined symbol: clang_getCompletionFixIt
```

Packages have been installed.

```
ii  libclang-3.9-dev                           1:3.9.1-19ubuntu1                            amd64        clang library - Development package
ii  libclang-4.0-dev                           1:4.0.1-10                                   amd64        clang library - Development package
ii  libclang-5.0-dev                           1:5.0.1-4                                    amd64        clang library - Development package
ii  libclang-6.0-dev                           1:6.0-1ubuntu2                               amd64        clang library - Development package
ii  libclang-7-dev                             1:7-3~ubuntu0.18.04.1                        amd64        clang library - Development package
ii  libclang-8-dev                             1:8-3~ubuntu18.04.1                          amd64        Clang library - Development package
ii  libclang-common-3.9-dev                    1:3.9.1-19ubuntu1                            amd64        clang library - Common development package
ii  libclang-common-4.0-dev                    1:4.0.1-10                                   amd64        clang library - Common development package
ii  libclang-common-5.0-dev                    1:5.0.1-4                                    amd64        clang library - Common development package
ii  libclang-common-6.0-dev                    1:6.0-1ubuntu2                               amd64        clang library - Common development package
ii  libclang-common-7-dev                      1:7-3~ubuntu0.18.04.1                        amd64        clang library - Common development package
ii  libclang-common-8-dev                      1:8-3~ubuntu18.04.1                          amd64        Clang library - Common development package
ii  libclang-dev                               1:6.0-41~exp5~ubuntu1                        amd64        clang library - Development package
ii  libclang-perl                              0.09-4build6                                 amd64        Perl bindings to the Clang compiler's indexing interface
ii  libclang1:amd64                            1:6.0-41~exp5~ubuntu1                        amd64        C, C++ and Objective-C compiler (LLVM based)
ii  libclang1-3.9:amd64                        1:3.9.1-19ubuntu1                            amd64        C interface to the clang library
ii  libclang1-3.9-dbg:amd64                    1:3.9.1-19ubuntu1                            amd64        clang library
ii  libclang1-4.0:amd64                        1:4.0.1-10                                   amd64        C interface to the clang library
ii  libclang1-4.0-dbg:amd64                    1:4.0.1-10                                   amd64        clang library (debug)
ii  libclang1-5.0:amd64                        1:5.0.1-4                                    amd64        C interface to the clang library
ii  libclang1-5.0-dbg:amd64                    1:5.0.1-4                                    amd64        clang library (debug)
ii  libclang1-6.0:amd64                        1:6.0-1ubuntu2                               amd64        C interface to the clang library
ii  libclang1-6.0-dbg:amd64                    1:6.0-1ubuntu2                               amd64        clang library (debug)
ii  libclang1-7:amd64                          1:7-3~ubuntu0.18.04.1                        amd64        C interface to the clang library
ii  libclang1-8                                1:8-3~ubuntu18.04.1                          amd64        C interface to the Clang library
```

**Comment by TsutomuNakamura** [comment]
Related #45?
