### ISSUE TITLE
Some vim plugins doesn't work on my Mac

### ISSUE THREAD

**Issue by TsutomuNakamura** [TsutomuNakamura/dotfiles#61]
## compile error with --system-libclang option
The error like bellow is occured when compile YouCompleteMe on my Mac.

```
> python3 ./install.py --clang-completer --system-libclang

Undefined symbols for architecture x86_64:
  "_clang_getCompletionFixIt", referenced from:
      YouCompleteMe::CompletionData::BuildCompletionFixIt(CXCodeCompleteResults*, unsigned long) in CompletionData.cpp.o
  "_clang_getCompletionNumFixIts", referenced from:
      YouCompleteMe::CompletionData::BuildCompletionFixIt(CXCodeCompleteResults*, unsigned long) in CompletionData.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/tsutomu/.dotfiles/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so] Error 1
make[2]: *** [ycm/CMakeFiles/ycm_core.dir/all] Error 2
make[1]: *** [ycm/CMakeFiles/ycm_core.dir/rule] Error 2
make: *** [ycm_core] Error 2
ERROR: the build failed.
```
https://github.com/Valloric/ycmd/issues/1141

## Decode error is occured when open a file from the pain of NERDTree
After YouCompleteme is compiled with the command `python3 ./install.py --clang-completer`, open a file from the pain of NERDTree, the error like below is occured.

```
Error detected while processing function <SNR>89_UpdateMatches:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tsutomu/.dotfiles/.vim/plugged/YouCompleteMe/python/ycm/youcompleteme.py", line 469, in UpdateMatches
    self.CurrentBuffer().UpdateMatches()
  File "/Users/tsutomu/.dotfiles/.vim/plugged/YouCompleteMe/python/ycm/buffer.py", line 88, in UpdateMatches
    self._diag_interface.UpdateMatches()
  File "/Users/tsutomu/.dotfiles/.vim/plugged/YouCompleteMe/python/ycm/diagnostic_interface.py", line 137, in UpdateMatches
    matches_to_remove = vimsupport.GetDiagnosticMatchesInCurrentWindow()
  File "/Users/tsutomu/.dotfiles/.vim/plugged/YouCompleteMe/python/ycm/vimsupport.py", line 252, in GetDiagnosticMatchesInCurrentWindow
    vim_matches = vim.eval( 'getmatches()' )
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
```
https://github.com/Valloric/YouCompleteMe/issues/2127

These errors haven't solved on my Mac yet.
Decided to skip to install YouCompleteMe on Mac till these problems were solved.
... I strongly wish to install YouCompleteMe on Mac.
I will fix this problem in the near future!!

**Comment by TsutomuNakamura** [comment]
Changed compile options of YouCompleteMe from Linux.
Completion of C lang might not be run on Mac but Python or JavaScript etc might be run.

Closed by #66
